# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\FaceRec\view\ui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1050, 600)
        MainWindow.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(250, 0, 801, 601))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(0, 0, 251, 601))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color: rgb(69, 90, 100);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_12.setText("")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.pushButton_register = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_register.setGeometry(QtCore.QRect(0, 90, 251, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_register.sizePolicy().hasHeightForWidth())
        self.pushButton_register.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_register.setFont(font)
        self.pushButton_register.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"    \n"
"    background-color: rgb(84, 110, 122);\n"
"\n"
"    border-radius:5px;\n"
"   \n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"QPushButton:hover\n"
"{\n"
"   \n"
"    background-color: rgb(127, 154, 167);\n"
"\n"
"    border-radius:5px;\n"
"   \n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover:pressed\n"
"{\n"
"    background-color:rgb(85,170,255);\n"
"    border:2px solid #3C80B1;\n"
"    border-radius:5px;\n"
"    color:white;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/pic/添加用户.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_register.setIcon(icon)
        self.pushButton_register.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_register.setObjectName("pushButton_register")
        self.pushButton_checkin = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_checkin.setGeometry(QtCore.QRect(0, 150, 251, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_checkin.sizePolicy().hasHeightForWidth())
        self.pushButton_checkin.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_checkin.setFont(font)
        self.pushButton_checkin.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"    \n"
"    background-color: rgb(84, 110, 122);\n"
"\n"
"    border-radius:5px;\n"
"   \n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"QPushButton:hover\n"
"{\n"
"   \n"
"    background-color: rgb(127, 154, 167);\n"
"\n"
"    border-radius:5px;\n"
"   \n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover:pressed\n"
"{\n"
"    background-color:rgb(85,170,255);\n"
"    border:2px solid #3C80B1;\n"
"    border-radius:5px;\n"
"    color:white;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/pic/checkin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_checkin.setIcon(icon1)
        self.pushButton_checkin.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_checkin.setObjectName("pushButton_checkin")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 20, 241, 41))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(69, 90, 100);\n"
"color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.pushButton_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(0, 390, 251, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_exit.sizePolicy().hasHeightForWidth())
        self.pushButton_exit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"    \n"
"    background-color: rgb(84, 110, 122);\n"
"\n"
"    border-radius:5px;\n"
"   \n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"QPushButton:hover\n"
"{\n"
"   \n"
"    background-color: rgb(127, 154, 167);\n"
"\n"
"    border-radius:5px;\n"
"   \n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover:pressed\n"
"{\n"
"    background-color:rgb(85,170,255);\n"
"    border:2px solid #3C80B1;\n"
"    border-radius:5px;\n"
"    color:white;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/pic/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_exit.setIcon(icon2)
        self.pushButton_exit.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_face_record = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_face_record.setGeometry(QtCore.QRect(0, 210, 251, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_face_record.sizePolicy().hasHeightForWidth())
        self.pushButton_face_record.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_face_record.setFont(font)
        self.pushButton_face_record.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"    \n"
"    background-color: rgb(84, 110, 122);\n"
"\n"
"    border-radius:5px;\n"
"   \n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"QPushButton:hover\n"
"{\n"
"   \n"
"    background-color: rgb(127, 154, 167);\n"
"\n"
"    border-radius:5px;\n"
"   \n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover:pressed\n"
"{\n"
"    background-color:rgb(85,170,255);\n"
"    border:2px solid #3C80B1;\n"
"    border-radius:5px;\n"
"    color:white;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/pic/facerecord.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_face_record.setIcon(icon3)
        self.pushButton_face_record.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_face_record.setObjectName("pushButton_face_record")
        self.pushButton_checkin_record = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_checkin_record.setGeometry(QtCore.QRect(0, 270, 251, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_checkin_record.sizePolicy().hasHeightForWidth())
        self.pushButton_checkin_record.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_checkin_record.setFont(font)
        self.pushButton_checkin_record.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"    \n"
"    background-color: rgb(84, 110, 122);\n"
"\n"
"    border-radius:5px;\n"
"   \n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"QPushButton:hover\n"
"{\n"
"   \n"
"    background-color: rgb(127, 154, 167);\n"
"\n"
"    border-radius:5px;\n"
"   \n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover:pressed\n"
"{\n"
"    background-color:rgb(85,170,255);\n"
"    border:2px solid #3C80B1;\n"
"    border-radius:5px;\n"
"    color:white;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/pic/checkinrecord.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_checkin_record.setIcon(icon4)
        self.pushButton_checkin_record.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_checkin_record.setObjectName("pushButton_checkin_record")
        self.label_logo = QtWidgets.QLabel(self.centralwidget)
        self.label_logo.setGeometry(QtCore.QRect(260, 0, 790, 600))
        self.label_logo.setStyleSheet("border-image: url(D:/FaceRec/view/pic/BS.png) 0 0 0 0 stretch stretch;")
        self.label_logo.setText("")
        self.label_logo.setObjectName("label_logo")
        self.pushButton_about = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_about.setGeometry(QtCore.QRect(0, 330, 251, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_about.sizePolicy().hasHeightForWidth())
        self.pushButton_about.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_about.setFont(font)
        self.pushButton_about.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"    \n"
"    background-color: rgb(84, 110, 122);\n"
"\n"
"    border-radius:5px;\n"
"   \n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"QPushButton:hover\n"
"{\n"
"   \n"
"    background-color: rgb(127, 154, 167);\n"
"\n"
"    border-radius:5px;\n"
"   \n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover:pressed\n"
"{\n"
"    background-color:rgb(85,170,255);\n"
"    border:2px solid #3C80B1;\n"
"    border-radius:5px;\n"
"    color:white;\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/pic/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_about.setIcon(icon5)
        self.pushButton_about.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_about.setObjectName("pushButton_about")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "基于Python+OpenCV的课堂人脸考勤系统"))
        self.pushButton_register.setText(_translate("MainWindow", "  人脸录入"))
        self.pushButton_checkin.setText(_translate("MainWindow", "  人脸识别"))
        self.label_8.setText(_translate("MainWindow", "课堂考勤"))
        self.pushButton_exit.setText(_translate("MainWindow", "  退出系统"))
        self.pushButton_face_record.setText(_translate("MainWindow", "  人脸库管理"))
        self.pushButton_checkin_record.setText(_translate("MainWindow", "  考勤管理"))
        self.pushButton_about.setText(_translate("MainWindow", "  首页"))
import resource_rc
